### ISSUE TITLE
How to replace the content in the configuration file?

### ISSUE THREAD

**Issue by guomaoqiu** [nervosnetwork/fiber#662]
Fnn Version: 0.5.0

When I tried to upgrade fnn, I found that the configuration files of the previous version were incompatible. So I read the release note and found that there were changes, but how can I replace the previous configuration?

1. Problems encountered

![Image](https://github.com/user-attachments/assets/b0b5ea30-edb7-45a7-b9d7-9c07f3d1b5c4)

2. Try to change the existing config.yml. How to replace the existing configuration?

Current configuration:
```
ckb:
  rpc_url: "https://testnet.ckb.dev/"
  udt_whitelist:
    - name: USDI
      script:
        code_hash: 0xcc9dc33ef234e14bc788c43a4848556a5fb16401a04662fc55db9bb201987037
        hash_type: type
        args: 0x71fd1985b2971a9903e4d8ed0d59e6710166985217ca0681437883837b86162f
      cell_deps:
        - tx_hash: 0xed7d65b9ad3d99657e37c4285d585fea8a5fcaf58165d54dacf90243f911548b
          index: 0
          dep_type: code
      auto_accept_amount: 1000000000
```

Configuration required for the new version:
```
ckb:
  rpc_url: "https://testnet.ckbapp.dev/"
  udt_whitelist:
    - name: RUSD
      script:
        code_hash: 0x1142755a044bf2ee358cba9f2da187ce928c91cd4dc8692ded0337efa677d21a
        hash_type: type
        args: 0x878fcc6f1f08d48e87bb1c3b3d5083f23f8a39c5d5c764f253b55b998526439b
      cell_deps:
        - type_id:
            code_hash: 0x00000000000000000000000000000000000000000000000000545950455f4944
            hash_type: type
            args: 0x97d30b723c0b2c66e9cb8d4d0df4ab5d7222cbb00d4a9a2055ce2e5d7f0d8b0f
      auto_accept_amount: 1000000000
```

**Comment by jjyr** [comment]
There are two ways to upgrade the config:

### 1 stay with cell_dep

just change the following code

``` yaml
# USDI
      cell_deps:
        - tx_hash: 0xed7d65b9ad3d99657e37c4285d585fea8a5fcaf58165d54dacf90243f911548b
           index: 0
           dep_type: code
```

to

``` yaml
# USDI
      cell_deps:
        - cell_dep:
            out_point:
              tx_hash: 0xed7d65b9ad3d99657e37c4285d585fea8a5fcaf58165d54dacf90243f911548b
              index: 0x0
            dep_type: code
```

### 2 use type_id to resolve cell_deps

The difference lies in how dependencies are configured.

When using cell_dep, if the script developer upgrades the on-chain script, the cell_dep becomes invalid, requiring you to update the configuration to prevent issues with the Fiber program.

However, if you use type_id to configure dependencies, Fiber resolves type_id to cell_deps automatically. Even if the on-chain script is upgraded, the configuration remains unchanged, and the Fiber program continues running seamlessly.

To find type_id of USDI:

0. open [explorer](https://testnet.explorer.nervos.org)
1. Find the tx [0xed7d65b9ad3d99657e37c4285d585fea8a5fcaf58165d54dacf90243f911548b](https://testnet.explorer.nervos.org/transaction/0xed7d65b9ad3d99657e37c4285d585fea8a5fcaf58165d54dacf90243f911548b) by tx_hash in the config.
2. Find the index 0 output cell, and click the cell info button.
3. Copy paste the Type Script of the cell.
4. Check the `code_hash` is `Type ID`.

``` json
{
    "code_hash": "0x00000000000000000000000000000000000000000000000000545950455f4944",
    "args": "0x97d30b723c0b2c66e9cb8d4d0df4ab5d7222cbb00d4a9a2055ce2e5d7f0d8b0f",
    "hash_type": "type"
}
```

Then use this info to write type_id config:

``` yaml
# USDI
      cell_deps:
        - type_id:
            code_hash: 0x00000000000000000000000000000000000000000000000000545950455f4944
            hash_type: type
            args: 0x97d30b723c0b2c66e9cb8d4d0df4ab5d7222cbb00d4a9a2055ce2e5d7f0d8b0f
```
