### ISSUE TITLE
[send_payment]: The allow_self_payment parameter affects unrelated XUDT channels

### ISSUE THREAD

**Issue by mfuuzy** [nervosnetwork/fiber#678]
version: 0.5.0
network: testnet

After repeated testing, sending CKB with the allow_self_payment parameter causes the Seal channel balance to change.No anomalies occur when the parameter is not included.Additionally, sending USDI affects the RUSD channel.

![Image](https://github.com/user-attachments/assets/849cb864-e3c0-4d68-8224-870ff03d3cdf)

### create invoce
```
{
    "id": 42,
    "jsonrpc": "2.0",
    "method": "new_invoice",
    "params": [
        {
            "amount": "0xba43b7400",
            "currency": "Fibt",
            "description": "node",
            "expiry": "0x2581",
            "final_cltv": "0x28",
            "payment_preimage": "0xc11111111111111111111111bb164b1b1141f011aefec11e1111111111111111",
            "hash_algorithm": "sha256"
        }
    ]
}
```

### send_payment
```
echo '{
    "id": 42,
    "jsonrpc": "2.0",
    "method": "send_payment",
    "params": [
        {
          "invoice": "fibt500000000001p49t2j4c5ujgfw0pnm6vkhwhejnk05jkgxmqq09qwnuhtfnk2e5yk8v26t4j7n37ysp4ztrgfhvar0ufe8up58t052s677d0z69nec4tzs7jpegpj0mzerxzk0smfxcfmauaxc56ram3p5c0y93f80wy37svrwzrrlj3fm888u8txur4f5hqmc4c8xwe3m3uuf8xaq037fjhrp260mgunqpawyjev3fjwqr6deg98zy66zzmgra2rytl0mqverpxva8g6chyy4uuyjv32e8hd7jwn2vgs6jwgw4377sks3q8zazjqm0n50jnxxr9qql7yfrd",
          "allow_self_payment": true
        }
    ]
}' \
| curl -H 'content-type: application/json' -d @- \
http://127.0.0.1:8227
```

**Comment by mfuuzy** [comment]
*补充描述*：
我们对 fiber channels 的 local_balance 和 remote_balance 的余额分别做了汇总监控，在测试发送 CKB 的时候，发现 Seal 的余额会跟着变动。


*问题复现*：
1. 使用 FIber RPC 创建 CKB invoice ， amount 设置 100 CKB.
2. send_payment 时加上 `allow_self_payment: true `  参数
3. 观察 Seal 通道余额会变化(这种变化应该不符合预期?)


*其他*:
send_payment 不带 allow_self_payment 参数没有影响

*配置参数*
```
ckb:
  rpc_url: "https://testnet.ckbapp.dev/"
  udt_whitelist:
    - name: USDI
      script:
        code_hash: 0xcc9dc33ef234e14bc788c43a4848556a5fb16401a04662fc55db9bb201987037
        hash_type: type
        args: 0x71fd1985b2971a9903e4d8ed0d59e6710166985217ca0681437883837b86162f
      cell_deps:
        - type_id:
            code_hash: 0x00000000000000000000000000000000000000000000000000545950455f4944
            hash_type: type
            args: 0xf0bad0541211603bf14946e09ceac920dd7ed4f862f0ffd53d0d477d6e1d0f0b
      auto_accept_amount: 10000000
    - name: RUSD
      script:
        code_hash: 0x1142755a044bf2ee358cba9f2da187ce928c91cd4dc8692ded0337efa677d21a
        hash_type: type
        args: 0x878fcc6f1f08d48e87bb1c3b3d5083f23f8a39c5d5c764f253b55b998526439b
      cell_deps:
        - type_id:
            code_hash: 0x00000000000000000000000000000000000000000000000000545950455f4944
            hash_type: type
            args: 0x97d30b723c0b2c66e9cb8d4d0df4ab5d7222cbb00d4a9a2055ce2e5d7f0d8b0f
      auto_accept_amount: 1000000000
    - name: SEAL
      script:
        code_hash: 0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb
        hash_type: type
        args: 0x122ae563f351bcaffef58bb57d5f4f863034721b361c645099501039a51d5936
      cell_deps:
        - type_id:
            code_hash: 0x00000000000000000000000000000000000000000000000000545950455f4944
            hash_type: type
            args: 0x44ec8b96663e06cc94c8c468a4d46d7d9af69eaf418f6390c9f11bb763dda0ae
      auto_accept_amount: 10000000000000
```
